# Generated by Django 4.0.6 on 2023-02-15 09:38

from django.db import migrations, models
import shortner.validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=220, validators=[shortner.validate.validate_url])),
                ('shortcode', models.CharField(blank=True, default='', max_length=15, unique=True)),
                ('update', models.DateField(auto_now=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
