# Generated by Django 4.0.4 on 2022-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='shortcode',
            field=models.CharField(blank=True, default='', max_length=15, unique=True),
        ),
    ]
